# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
	config.vm.provision "shell",path: "bootstrap.sh"
	config.vm.define "web" do |web|
		web.vm.box = "ubuntu/bionic64"
		web.vm.hostname = "web"
	end
	config.vm.define "db" do |db|
 		db.vm.box = "ubuntu/bionic64"
		db.vm.hostname = "db"
		db.vm.provision "shell",path: "bootstrap-db.sh"
	end
end
