# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|

	config.env.enable
	config.vm.box = ENV['BOX_NAME']
	
	config.vm.define "web" do |web|
		web.vm.hostname = "web"
	end
	config.vm.define "db" do |db|
		db.vm.hostname = "db"
	end
end
