# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
	config.vm.define "web" do |web|
		web.vm.box = "ubuntu/bionic64"
		web.vm.hostname = "web"
		web.vm.network "private_network", ip: "192.168.50.4"
	end
	config.vm.define "db" do |db|
 		db.vm.box = "ubuntu/bionic64"
		db.vm.hostname = "db"
	end
end
