# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|

	config.trigger.before :up do |trigger|
		trigger.name = "Finished message"
		trigger.info = "Environment is up!!"
	end

	config.vm.box = "ubuntu/bionic64"

	config.vm.define "web" do |web|
		web.vm.hostname = "web"
	end
	config.vm.define "db" do |db|
		db.vm.hostname = "db"
	end
end
