Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.provision :docker
  config.vm.provision :docker_compose,
    compose_version: "1.24.0",
    yml: "/vagrant/docker-compose.yml",
    run: "always"

  config.vm.provider :virtualbox do |virtualbox|
    virtualbox.name = "filesystem-kv"
  end
  config.vm.network "forwarded_port",
          guest: 8200,
          host:  8200

  config.vm.synced_folder './data', '/vault/data',
    owner: 100,
    group: 1000
end
